### ISSUE TITLE
Newline required at end of file

### ISSUE THREAD

**Issue by rasmniel** [wolfgang42/rockstar-js#25]
When having trouble compiling, I noticed that it is required to end the file with a new line - which may contain whitespace - otherwise `peg` fails.
Not that it is a great deal of trouble, but it may be worth noting in the readme in order to avoid confusion. I realize it says so in the spec, but the error message does not explain this.

**Comment by wolfgang42** [comment]
Yes, the parser requires a newline at the end of the file. However you
aren't supposed to have to add it at the end; the compiler is supposed to
add it for you during the compile. I must have lost this feature at some
point but didn't notice because my editor always adds one when I save.
>
>
I will patch this bug so you don't need to do this any more. Thanks for
bringing this to my attention.
